
theme: "jekyll-theme-slate"
title: "Ketch Partners - HANA Express Red Hat Binary Install Guide"
description: "Leveraging HANA Express Installation Instructions to Create On-Premise HANA XSA Server and Application Components"
show_downloads: false
markdown: kramdown
google_analytics: UA-113301314-1
github: [metadata]
repository: ketchpartners/hanaexpress
url: "https://ketchpartners.github.io/hanaexpress"
baseurl: "/"
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
disqus: davebeach
plugins:
  - "jekyll-github-metadata"
  - "jekyll-watch"
  - "jekyll-coffeescript"
  - "disqus-for-jekyll"
defaults:
  -
    scope:
      path: "/assets/images"
    values:
      image: true
  -
    scope:
      path: ""
    values:
      layout: "default"
      page.author: "David Beach"
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "bower_components", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

